### ISSUE TITLE
JAVA_HOME plus PATH necessary to run validation

### ISSUE THREAD

**Issue by thorstenkampe** [Umoxfo/vscode-w3cvalidation#14]
There seems to be some kind of design flaw: you have to set JAVA_HOME and PATH in order to run this extension. Similar Java apps need either one or the other since one can easily be derived from the other. 

My problem is that I'm running in a portable environment. I've set `vscode-w3cvalidation.javaHome` but I also need to set an environment variable outside of VSCode.

**Comment by Umoxfo** [comment]
I am sorry.

I decided to remove the `vscode-w3cvalidation.javaHome` option for a few reasons.

**Comment by Umoxfo** [comment]
I fixed it in v2.5.0.
