### ISSUE TITLE
validator does not show error

### ISSUE THREAD

**Issue by thorstenkampe** [Umoxfo/vscode-w3cvalidation#15]
Given the test document below, `vscode-w3cvalidation` does not display an error although the binary checker (`vnu.jar`) does:
> Error: A "script" element with a "src" attribute must not have a "type" attribute whose value is anything other than the empty string, a JavaScript MIME type, or "module".
From line 6, column 5; to line 6, column 45 in resource file:/test.html

```html
<!DOCTYPE html>
<html lang="de">

<head>
    <title>test</title>
    <script src="test.py" type="text/python"></script>
</head>

</html>
```

**Comment by Umoxfo** [comment]
In v2.4.0, the Nu Html Checker v18.11.5 which is the official latest release is used.

In v2.5.0, it has been updated to the latest preview release.
