### ISSUE TITLE
how does it work

### ISSUE THREAD

**Issue by ozo7** [Umoxfo/vscode-w3cvalidation#18]
I installed it and do not know how to check that it is working. "Just open html page". Yes, of course, nothing happens, I remove a closing tag, nothing happens. What is a test case to prove it is working?

**Comment by Umoxfo** [comment]
I need a screenshot of the problem.

**Comment by ozo7** [comment]
From my face, the help section, my google page, my fingers? ok. just let us not think about this anymore.
