### ISSUE TITLE
Activation only for HTML file

### ISSUE THREAD

**Issue by exprosic** [Umoxfo/vscode-w3cvalidation#23]
https://github.com/Umoxfo/vscode-w3cvalidation/blob/3dba06c9ab95f1f0623ded09fb764bf4ae0d5494/package.json#L25

Currently this extension is enabled right after VSCode get opened and immediately write stuffs to the Output panel.

**Comment by Umoxfo** [comment]
Fixed 41ae01f2c9378963860cbeeca23000704c7ffa96
