### ISSUE TITLE
Question: Is this also for debian linux?

### ISSUE THREAD

**Issue by jluisgarcia** [Umoxfo/vscode-w3cvalidation#37]
I am using VScodium (same as VScode without Microsoft mark).
Is this extension valid for use with Debian Linux?
Is this installation valid? >> ext install Umoxfo.vscode-w3cvalidation
I would like to make sure before I try and break something.
Thanks.

**Comment by Umoxfo** [comment]
This extension will work if Java 8 or later (the latest LTS version is recommended) is installed.

**Comment by jluisgarcia** [comment]
It's not found in the extensions marketplace. However all other typical extensions are found. Like Prettier, etc.
![codium-1](https://user-images.githubusercontent.com/24752182/134557175-5819175b-882d-4b52-a2c8-c1c7c7c903b1.png)

I am using Visual Studio Codium which is the same as VSCode without telemetry.
https://github.com/VSCodium/vscodium
My system is Debian 10
I have just installed OpenJDK 11
The main issue is that it is not found in the marketplace.

**Comment by Umoxfo** [comment]
Ref #33
