### ISSUE TITLE
Can't set directory for JRE

### ISSUE THREAD

**Issue by TalhaJamil23** [Umoxfo/vscode-w3cvalidation#6]
When I installed this plugin it prompted me to download JRE through this link ("https://www.oracle.com/technetwork/java/javase/downloads/index.html"), after downloading and instating Java SE 12 I put its install directory into VS Code's setting ("C:\Program Files\Java\jdk-12") and restarted VS Code, but it doesn't seem to work, every time VS Code runs I get the same errors prompting me download and install JRE from that same link, I even checked the setting.JSON file and the path is updated there, any help would be greatly appreciated, thank you.

**Comment by arhipov-rp** [comment]
For Windows OS set the following environment variables:
JAVA_HOME: C:\Program Files\Java\jdk-12
PATH: your-unique-entries;%JAVA_HOME%\bin

**Comment by TalhaJamil23** [comment]
Thanks.. I'll try that

**Comment by guillermoarellano** [comment]
This worked for me. Thanks!
