### ISSUE TITLE
Missing JDK

### ISSUE THREAD

**Issue by KodaLover** [Umoxfo/vscode-w3cvalidation#7]
I have installed this extension, and have (intentional) errors in my html coding. Have saved the file as an html file, but still it shows 0 errors.  I am very new at this.  Please help.

**Comment by Umoxfo** [comment]
I need a screenshot of the problem.

**Comment by KodaLover** [comment]
![chrome_2019-05-19_18-17-49](https://user-images.githubusercontent.com/26800003/57991294-be52ec80-7a62-11e9-9662-0f01849f7206.png)

**Comment by KodaLover** [comment]
As you can see above, there are two errors, and yet the problems panel shows 0 errors.

**Comment by Umoxfo** [comment]
#6 
You should install JDK and set the environment variables.

**Comment by Spanoudakhs** [comment]
Same problem here on ubuntu 18.04 bionic beaver :
![Screenshot from 2019-08-07 07-21-58](https://user-images.githubusercontent.com/45520375/62594926-09073680-b8e5-11e9-9745-1e39fec27696.png)
You should add info about linux also (not only windows) .

**Comment by devmyqi** [comment]
I have the same Error, installed JDK-13 and set the %PATH% as described in the extensions details
![vscode-jdk-error](https://user-images.githubusercontent.com/42442939/65685966-90f6fa80-e063-11e9-8226-279152598552.PNG)

**Comment by Umoxfo** [comment]
I decided to remove the `vscode-w3cvalidation.javaHome` option for a few reasons.

**Comment by Spanoudakhs** [comment]
> I decided to remove the `vscode-w3cvalidation.javaHome` option for a few reasons.

Thx . It works now and does not need the `vscode-w3cvalidation.javaHome` option .

**Comment by devmyqi** [comment]
> > I decided to remove the `vscode-w3cvalidation.javaHome` option for a few reasons.
> Thx . It works now and does not need the `vscode-w3cvalidation.javaHome` option .

What did you do that it works? I just removed the extension and re-installed it again. Still got the error message "Java runtime could not be located".

**Comment by Spanoudakhs** [comment]
> What did you do that it works? I just removed the extension and re-installed it again. Still got the error message "Java runtime could not be located".

I just enabled the disabled extension and it worked .

**Comment by devmyqi** [comment]
> 
> 
> > What did you do that it works? I just removed the extension and re-installed it again. Still got the error message "Java runtime could not be located".
> 
> I just enabled the disabled extension and it worked .

unfortunately, not for me, i still have that annoying error :-(

**Comment by Umoxfo** [comment]
Fixed in v2.5.0.
The `vscode-w3cvalidation.javaHome` option should also work.

**Comment by NBKRedSpy** [comment]
Have a similar issue with Windows 10.   The java process is running, but doesn't seem to be validating the html.  

Problems pane shows no problems.  Also disabled all other extensions just in case.

Process running:
java -jar c:\Users\<<removed>>\.vscode\extensions\umoxfo.vscode-w3cvalidation-2.5.0\server\service\jetty-home/start.jar

Example invalid index.html file in workspace:
<body></body>
<html></html>
<html></html>
